In [1]:
import numpy as np

In [3]:
A = np.ndarray([4,16])
A.fill(0.001)
A

array([[0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001,
        0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001],
       [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001,
        0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001],
       [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001,
        0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001],
       [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001,
        0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]])

In [6]:
B = np.ndarray([16,1])
B[0,0] = 161
B[1,0] = 161
B[2,0] = 163
B[3,0] = 159
B[4,0] = 161
B[5,0] = 161
B[6,0] = 155
B[7,0] = 157
B[8,0] = 157
B[9,0] = 157
B[10,0] = 159
B[11,0] = 159
B[12,0] = 161
B[13,0] = 161
B[14,0] = 159
B[15,0] = 157
B

array([[161.],
       [161.],
       [163.],
       [159.],
       [161.],
       [161.],
       [155.],
       [157.],
       [157.],
       [157.],
       [159.],
       [159.],
       [161.],
       [161.],
       [159.],
       [157.]])

In [8]:
A.dot(B)

array([[2.548],
       [2.548],
       [2.548],
       [2.548]])